apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: test-project
spec:
  selector:
    matchLabels:
      app: test-project
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: test-project
    spec:
      containers:
        - name: test-project
          image: aayushiverma1210/rest-application:test-project
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
# The port that the container is running on in the cluster
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: test-project
spec:
  selector:
    app: test-project
  ports:
    - protocol: "TCP"
      port: 8085 # The port that the service is running on in the cluster
      targetPort: 8085 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
